# Generated by Django 5.1.4 on 2024-12-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nerd', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
